# Generated by Django 4.2.1 on 2023-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['time_created', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='news_category',
            options={'ordering': ['name'], 'verbose_name': 'Категория новостей', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news_category',
            name='discription',
            field=models.TextField(max_length=100, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='news_category',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Категория'),
        ),
    ]
