# Generated by Django 4.2.1 on 2023-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0004_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.TextField(max_length=350, verbose_name='Текст комментария')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_created', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=15000, verbose_name='Текст новости'),
        ),
    ]
