# Generated by Django 4.2.1 on 2023-05-13 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsblock', '0006_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='news_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='newsblock.news', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
