# Generated by Django 4.2.1 on 2023-05-14 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsblock', '0007_comments_news_id_comments_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsblock.news', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
