# Generated by Django 4.2.1 on 2023-05-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0008_news_slug_alter_comments_news_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
