# Generated by Django 4.2.1 on 2023-05-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0009_alter_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
