# Generated by Django 4.2.1 on 2023-05-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0010_remove_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
