# Generated by Django 4.2.1 on 2023-06-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0011_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_categories_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsblock.news_category', verbose_name='Категория'),
        ),
    ]
