# Generated by Django 4.2.1 on 2023-06-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0012_alter_news_news_categories_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Категория обсуждения')),
                ('discription', models.TextField(max_length=100, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория обсуждения',
                'verbose_name_plural': 'Категории обсуждения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок обсуждения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.TextField(max_length=15000, verbose_name='Текст обсуждения')),
                ('image', models.ImageField(blank=True, upload_to='photos', verbose_name='Фотография')),
                ('is_closed', models.BooleanField(default=True, verbose_name='Отображение')),
                ('topic_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsblock.news_category', verbose_name='Категория обсуждения')),
            ],
            options={
                'verbose_name': 'Обсуждение',
                'verbose_name_plural': 'Обсуждение',
                'ordering': ['-time_created', 'title'],
            },
        ),
    ]
