# Generated by Django 4.2.1 on 2023-06-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0013_topic_category_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_category_id',
        ),
        migrations.DeleteModel(
            name='Topic_Category',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
