# Generated by Django 4.2.1 on 2023-06-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsblock', '0014_remove_topic_topic_category_id_delete_topic_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_categories_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsblock.news_category', verbose_name='Категория новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок новости'),
        ),
        migrations.AlterField(
            model_name='news_category',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Категория новости'),
        ),
    ]
