# Generated by Django 4.2.1 on 2023-06-15 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsblock', '0015_alter_news_news_categories_id_alter_news_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='News_Comment',
        ),
    ]
