# Generated by Django 4.2.1 on 2023-06-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumblock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
    ]
