# Generated by Django 4.2.1 on 2023-06-15 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumblock', '0003_topic_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.TextField(max_length=350, verbose_name='Текст комментария')),
                ('Topic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forumblock.topic', verbose_name='Обсуждение')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['time_created'],
            },
        ),
    ]
