# Generated by Django 4.2.1 on 2023-06-15 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumblock', '0004_forum_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum_Comments',
            new_name='Topic_Comment',
        ),
    ]
