# Generated by Django 4.2.1 on 2023-06-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumblock', '0005_rename_forum_comments_topic_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic_comment',
            old_name='Topic_id',
            new_name='topic_id',
        ),
    ]
