# Generated by Django 4.2.1 on 2023-05-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameblock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default=0, max_length=16, verbose_name='Никнейм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gameblock.team', verbose_name='ID команды'),
        ),
    ]
