# Generated by Django 4.2.1 on 2023-05-12 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameblock', '0002_player_nickname_alter_player_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gameblock.team', verbose_name='ID команды'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID игрока, как пользователя'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to='teamlogos', verbose_name='Логотип команды'),
        ),
    ]
