# Generated by Django 4.2.1 on 2023-05-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameblock', '0004_alter_player_team_id_alter_player_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='discription',
            field=models.TextField(max_length=2000, verbose_name='Описание дисциплины'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gameblock.team', verbose_name='Команда'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=25, verbose_name='Название турнира')),
                ('discription', models.TextField(max_length=2000, verbose_name='Описание турнира')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Оконченность')),
                ('team_id', models.ManyToManyField(blank=True, related_name='tournaments', to='gameblock.team', verbose_name='Участники')),
                ('winner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_tournaments', to='gameblock.team', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['id'],
            },
        ),
    ]
