# Generated by Django 4.2.1 on 2023-05-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameblock', '0006_alter_tournament_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
