# Generated by Django 4.2.1 on 2023-05-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameblock', '0011_alter_game_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_id',
            field=models.ManyToManyField(related_name='games', to='gameblock.team', verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='Playerscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Очки')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gameblock.game', verbose_name='Игра')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gameblock.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Очки',
                'verbose_name_plural': 'Очки',
                'ordering': ['-id'],
            },
        ),
    ]
